version: '3'
services:
  coloring-images-generator:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./download_creation:/app/download_creation
    restart: always
    command: streamlit run main.py --server.baseUrlPath /coloring

