from openai import OpenAI

def image_prompt(theme: str) -> str:
    """
    Generate a prompt for creating a children's coloring book page image based on a given theme.

    This function constructs a detailed prompt for an AI image generation model,
    specifying the requirements for a coloring book page suitable for children.
    The prompt emphasizes simplicity, clarity, and suitability for printing.

    Args:
        theme (str): The theme for the coloring book page. This theme will be
                     incorporated into the prompt to guide the image generation.

    Returns:
        str: A formatted string containing the complete prompt for image generation.
             The prompt includes specifications for style, composition, and printing considerations.

    Example:
        >>> prompt = image_prompt("Underwater Adventure")
        >>> print(prompt)
        Create a black and white line drawing suitable for a children's coloring book page.
        The image should feature a simple, cute cartoon-style in a balanced composition.
        The theme is 'Underwater Adventure'.
        Ensure the design has clear, bold lines and simple shapes that will look good when scaled up for printing on A4 paper.
        Avoid intricate details that may be lost when printed.
    """

    return f"""
    Create a black and white line drawing suitable for a children's coloring book page.
    The image should feature a simple, cute cartoon-style in a balanced composition.
    The theme is '{theme}'.
    Ensure the design has clear, bold lines and simple shapes that will look good when scaled up for printing on A4 paper.
    Avoid intricate details that may be lost when printed.
    """

def generate_image(client: OpenAI, prompt: str) -> str:
    """
    Generate an image using OpenAI's DALL-E 3 model based on the given prompt.

    This function sends a request to the OpenAI API to generate an image
    using the DALL-E 3 model. It uses the provided prompt to guide the
    image generation process.

    Args:
        client (OpenAI): An initialized OpenAI client instance.
        prompt (str): A string describing the image to be generated.

    Returns:
        str: The URL of the generated image.

    Raises:
        ValueError: If no image is generated by the API.
        openai.OpenAIError: For any API-related errors (e.g., rate limiting, authentication issues).

    Example:
        >>> client = OpenAI(api_key="your-api-key")
        >>> prompt = "A cute cartoon elephant playing with a red ball"
        >>> image_url = generate_image(client, prompt)
        >>> print(image_url)
        https://oaidalleapiprodscus.blob.core.windows.net/private/...
    """
    response = client.images.generate(
        model="dall-e-3",
        prompt=prompt,
        size="1024x1024",
        quality="standard",
        n=1
    )
    if response.data:
        return response.data[0].url
    else:
        raise ValueError("No image generated")
